//! One cosigner, serving one wallet.
//!
//! [`Cosigner`] is that wallet: its keys, its FROST ceremonies, its Ark sessions, loaded from its
//! seal when the process opens. Tenancy is deliberately absent — the runtime this is built for
//! hands an instance a filesystem already scoped to one client, so there is nothing here to route
//! between — and so are outbound sockets: the ASP is driven by whoever calls, and waking a device
//! is the host's. What is left talks to its [`store`] and to its caller.

pub mod asp;
pub mod config;
pub mod cosigner;
pub mod delegate;
pub mod grpc;
pub mod handlers;
pub mod host;
pub mod escrow;
pub mod escrow_session;
pub mod evidence;
pub mod policy;
pub mod service_stream;
pub mod session;
pub mod store;
pub mod types;
mod util;

pub use cosigner::Cosigner;
pub use types::ArkTxEntry;

/// The message shapes, generated by prost from `proto/mpc_wallet.proto`.
///
/// `build.rs` runs tonic-build with the client and server generators switched off, so what lands
/// here is pure prost with no transport in it — which is what makes the same types usable from a
/// `wasm32-wasip2` guest, where tonic does not build at all.
pub mod wallet_proto {
    #![allow(clippy::all)]
    include!(concat!(env!("OUT_DIR"), "/mpc_wallet.rs"));
}
